import re
from typing import List, Dict, Any

def find_best_verbatim_match(hallucinated_quote: str, original_reviews: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Finds the review with the highest text overlap/intersection to swap in place of 
    a hallucinated quote.
    """
    if not hallucinated_quote or not original_reviews:
        return {}
        
    best_match = None
    max_overlap = -1
    
    # Tokenize the hallucinated quote for word matching
    quote_words = set(re.findall(r'\w+', hallucinated_quote.lower()))
    
    for r in original_reviews:
        cleaned_text = r.get("cleaned_text", "")
        if not cleaned_text:
            continue
            
        # Check for direct verbatim substring containment
        if hallucinated_quote.lower() in cleaned_text.lower() or cleaned_text.lower() in hallucinated_quote.lower():
            # Perfect direct match
            return r
            
        # Otherwise run word overlap matching
        review_words = set(re.findall(r'\w+', cleaned_text.lower()))
        overlap = len(quote_words.intersection(review_words))
        
        if overlap > max_overlap:
            max_overlap = overlap
            best_match = r
            
    return best_match if best_match else original_reviews[0]

def validate_and_ground_quotes(llm_insight: Dict[str, Any], original_reviews: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Validates all supporting quotes generated by the LLM.
    Replaces any hallucinated or modified text with verbatim matching entries.
    """
    if not llm_insight or "supporting_quotes" not in llm_insight:
        return llm_insight
        
    grounded_quotes = []
    seen_texts = set()
    
    for quote in llm_insight.get("supporting_quotes", []):
        quote_text = quote.get("text", "").strip()
        if not quote_text:
            continue
            
        # Check if this exact text exists in original reviews
        is_verbatim = False
        matching_record = None
        for r in original_reviews:
            if quote_text.lower() == r.get("cleaned_text", "").lower().strip():
                is_verbatim = True
                matching_record = r
                break
                
        if is_verbatim and matching_record:
            # Standard verified quote
            verbatim_text = matching_record.get("cleaned_text", "")
            platform = matching_record.get("platform", "play_store")
            timestamp = matching_record.get("timestamp", "")
        else:
            # Hallucination detected or text slightly modified. Find the closest match.
            best_match = find_best_verbatim_match(quote_text, original_reviews)
            if best_match:
                verbatim_text = best_match.get("cleaned_text", "")
                platform = best_match.get("platform", "play_store")
                timestamp = best_match.get("timestamp", "")
            else:
                continue # Skip if no matching review exists
                
        if verbatim_text not in seen_texts:
            seen_texts.add(verbatim_text)
            grounded_quotes.append({
                "text": verbatim_text,
                "source_platform": platform,
                "timestamp": timestamp
            })
            
    llm_insight["supporting_quotes"] = grounded_quotes
    return llm_insight

def calculate_theme_confidence(cluster_reviews: List[Dict[str, Any]], avg_distance: float = None) -> float:
    """
    Calculates a statistical confidence score (0.0 to 1.0) for a behavioral theme.
    
    Formula:
       C = 0.4 * min(1.0, S/100) + 0.3 * (D / D_max) + 0.3 * V
    """
    S = len(cluster_reviews)
    if S == 0:
        return 0.0
        
    # 1. Size Score (min 1.0 at 100 entries)
    size_score = min(1.0, S / 100.0)
    
    # 2. Platform Diversity Score (Max D_max = 3: play_store, app_store, reddit)
    platforms = set(r.get("platform", "play_store") for r in cluster_reviews)
    diversity_score = len(platforms) / 3.0
    
    # 3. Density Score (Vector average similarity proxy)
    # Cosine distance ranges from 0.0 (identical) to 2.0 (opposite).
    # Similarity = 1.0 - distance.
    if avg_distance is not None:
        avg_similarity = max(0.0, min(1.0, 1.0 - avg_distance))
    else:
        # Default proxy if distance is not provided
        avg_similarity = 0.8
        
    confidence = (0.4 * size_score) + (0.3 * diversity_score) + (0.3 * avg_similarity)
    return round(confidence, 2)
